import refs from '../../refs/refs';
import brand_info from '../../../views/layouts/brand.hbs';
import form_brand from '../../..//views/partials/brand/formFittingInShowroom.hbs';
import brand_our_advantages from '../../..//views/partials/brand/ourAdvantages.hbs';
import card_brand_our_advantages from '../../..//views/partials/brand/cardBrandOurAdvantages.hbs';
import brandOurAdvantagesCard from '../../json/brandOurAdvantagesCard.json';
const cardBrandOurAdvantages = card_brand_our_advantages(brandOurAdvantagesCard);
const formBrand = form_brand();
const brandOurAdvantages = brand_our_advantages({ formBrand, cardBrandOurAdvantages });
const brandInfo = brand_info({ brandOurAdvantages });
refs.brand.insertAdjacentHTML('beforeend', brandInfo);
