export default {
  // mainfoto: document.querySelector('.js-mainfoto'),
  descriptiontitle: document.querySelector('.js-description'),
  questanswer: document.querySelector('.question-body'),
  form: document.querySelector('.js-question-form'),
  textarea: document.querySelector('.js-question-form textarea'),
  inputname: document.querySelector('.input-name'),

  bodyEl: document.querySelector('body'),
  mainEL: document.querySelector('main'),
  delheadnav: document.querySelector('.js-nav-product'),

  main: document.querySelector('main'),
  bodyEl: document.querySelector('body'),
  mainEL: document.querySelector('main'),
  plusLink: document.querySelectorAll('.open-menu'),
  minusLink: document.querySelectorAll('.footer__mobile-icon-menu-close'),
  openSubMenu: document.querySelector('.footer__mobile-list-dropdown'),
  isOpenIcon: document.querySelector('.footer__mobile-icon-menu-open'),
  removeIconPlus: document.querySelectorAll('.footer__mobile-icon-position-relative'),
  iconMenu: document.querySelector('.footer__mobile-icon-menu'),
  openList: document.querySelectorAll('.footer__mobile-list'),
  closeOpenPlus: document.querySelectorAll('.footer__mobile-list-item-plus'),
  openSubMenu: document.querySelectorAll('.footer__mobile-list-dropdown'),
  dropDown: document.querySelectorAll('.footer__mobile-submenu'),
  inputStorageMobile: document.querySelectorAll('.footer__mobile-form-input'),
  inputStorageDesktop: document.querySelectorAll('.footer__desktop-form-input'),
  checkBoxIcon: document.querySelector('.footer__desktop-license-icon-checkbox'),
  agreeActive: document.querySelector('.agree'),
  mobileSubmitBtn: document.querySelector('.footer__mobile-form'),
  desktopSubmitBtn: document.querySelector('.footer__desktop-form'),
  footerSectionDesktop: document.querySelector('.footer__desktop'),
  testIdInput: document.querySelectorAll('#id'),
  desktop: document.querySelectorAll('.footer__desktop-list'),
  main: document.querySelector('main'),
  bodyEl: document.querySelector('body'),
  mainEL: document.querySelector('main'),
  setList: document.querySelector('.js-videoset'),

  // videobox: document.querySelector('.js-videobox'),
  // overlay: document.querySelector('.videobox__overlay'),
  // videoEl: document.querySelector('.video-set__video'),
  // BtnEl: document.querySelector('[data-action="close-videobox"]')
};
