export default {
  openList: document.querySelectorAll('.footer__mobile-list'),
  closeOpenPlus: document.querySelectorAll('.footer__mobile-list-item-plus'),
  openSubMenu: document.querySelectorAll('.footer__mobile-list-dropdown'),
  dropDown: document.querySelectorAll('.footer__mobile-submenu'),
  inputStorageMobile: document.querySelectorAll('.footer__mobile-form-input'),
  inputStorageDesktop: document.querySelectorAll('.footer__desktop-form-input'),
  checkBoxIcon: document.querySelector('.footer__desktop-license-icon-checkbox'),
  agreeActive: document.querySelector('.agree'),
  mobileSubmitBtn: document.querySelector('.footer__mobile-form'),
  desktopSubmitBtn: document.querySelector('.footer__desktop-form'),
  footerSectionDesktop: document.querySelector('.footer__desktop'),
  testIdInput: document.querySelectorAll('#id'),
  desktop: document.querySelectorAll('.footer__desktop-list'),
  main: document.querySelector('main'),
  bodyEl: document.querySelector('body'),
  mainEL: document.querySelector('main'),
  setList: document.querySelector('.js-videoset'),
  // ----- header-start ------
  headerEl: document.querySelector('.js-header'),
  buttonMobEl: document.querySelector('.js-header-button'),
  svgMobEl: document.querySelectorAll('.js-header-button__svg'),
  svgBinEl: document.querySelector('.js-header-svg-bin'),
  socialMobEl: document.querySelector('.js-header-social-list-mobile'),
  logoSvgEl: document.querySelector('.js-header-logo__svg'),
  logoTextEl: document.querySelector('.js-header-logo__text'),
  listTextEl: document.querySelectorAll('.js-header-list__text'),
  svgFavoritesEl: document.querySelector('.js-header-svg-favorites'),
  navigationEl: document.querySelector('.js-header-navigation'),
  navListEl: document.querySelector('.js-header-navigation-list'),
  navSublistEl: document.getElementsByClassName('js-header-navigation-sublist'),
  wrapperEl: document.querySelector('.js-header-wrapper'),
  navLinkEl: document.getElementsByClassName('js-header-navigation-link'),
  contactEl: document.querySelector('#header-contact'),
  showroomEl: document.querySelector('#header-showroom'),
  catalogNewEl: document.querySelector('#header-catalog-new'),
  favoritesEl: document.querySelector('#header-favorites'),
  // ----- header-end ------
  // videobox: document.querySelector('.js-videobox'),
  // overlay: document.querySelector('.videobox__overlay'),
  // videoEl: document.querySelector('.video-set__video'),
  // BtnEl: document.querySelector('[data-action="close-videobox"]')
};
