import '../../images/svg/exampl.svg';

//============header======================//
import '../../images/svg/header.svg';
import '../../images/img/header/header-arrow.svg';
//=========== hero========================//

//=========== hero========================//
import '../../images/img/page-hero/mobile/hero-title-01/hero-title-mobile-01.jpg';
import '../../images/img/page-hero/mobile/hero-title-01/hero-title-mobile-01@2x.jpg';
import '../../images/img/page-hero/mobile/hero-title-02/hero-title-mobile-02.jpg';
import '../../images/img/page-hero/mobile/hero-title-02/hero-title-mobile-02@2x.jpg';
import '../../images/img/page-hero/mobile/hero-title-03/hero-title-mobile-03.jpg';
import '../../images/img/page-hero/mobile/hero-title-03/hero-title-mobile-03@2x.jpg';
import '../../images/img/page-hero/mobile/hero-title-04/hero-title-mobile-04.jpg';
import '../../images/img/page-hero/mobile/hero-title-04/hero-title-mobile-04@2x.jpg';
import '../../images/img/page-hero/desktop/hero-title-01/hero-title-desktop-01.jpg';
import '../../images/img/page-hero/desktop/hero-title-01/hero-title-desktop-01@2x.jpg';
import '../../images/img/page-hero/desktop/hero-title-02/hero-title-desktop-02.jpg';
import '../../images/img/page-hero/desktop/hero-title-02/hero-title-desktop-02@2x.jpg';
import '../../images/img/page-hero/desktop/hero-title-03/hero-title-desktop-03.jpg';
import '../../images/img/page-hero/desktop/hero-title-03/hero-title-desktop-03@2x.jpg';
import '../../images/img/page-hero/desktop/hero-title-04/hero-title-desktop-04.jpg';
import '../../images/img/page-hero/desktop/hero-title-04/hero-title-desktop-04@2x.jpg';
import '../../images/svg/hero-svg-original/hero-arrow-left.svg';
import '../../images/svg/hero-svg-original/hero-arrow-right.svg';
import '../../images/svg/clients-svg-original/clients-arrow-right.svg';
import '../../images/svg/clients-svg-original/clients-arrow-right.svg';

// ================content=========================//
// Mobile
import '../../images/img/home/content/mobile/img-mob_1.jpg';
import '../../images/img/home/content/mobile/img-mob_1@2x.jpg';
import '../../images/img/home/content/mobile/img-mob_2.jpg';
import '../../images/img/home/content/mobile/img-mob_2@2x.jpg';
import '../../images/img/home/content/mobile/img-mob_3.jpg';
import '../../images/img/home/content/mobile/img-mob_3@2x.jpg';
import '../../images/img/home/content/mobile/img-mob_4.jpg';
import '../../images/img/home/content/mobile/img-mob_4@2x.jpg';
import '../../images/img/home/content/mobile/img-mob_5.jpg';
import '../../images/img/home/content/mobile/img-mob_5@2x.jpg';
import '../../images/img/home/content/mobile/img-mob_6.jpg';
import '../../images/img/home/content/mobile/img-mob_6@2x.jpg';
import '../../images/img/home/content/mobile/img-mob_7.jpg';
import '../../images/img/home/content/mobile/img-mob_7@2x.jpg';
import '../../images/img/home/content/mobile/img-mob_8.jpg';
import '../../images/img/home/content/mobile/img-mob_8@2x.jpg';
import '../../images/img/home/content/mobile/img-mob_9.jpg';
import '../../images/img/home/content/mobile/img-mob_9@2x.jpg';
import '../../images/img/home/content/mobile/img-mob_10.jpg';
import '../../images/img/home/content/mobile/img-mob_10@2x.jpg';
// Desktop
import '../../images/img/home/content/desk/img_1.jpg';
import '../../images/img/home/content/desk/img_1@2x.jpg';
import '../../images/img/home/content/desk/img_2.jpg';
import '../../images/img/home/content/desk/img_2@2x.jpg';
import '../../images/img/home/content/desk/img_3.jpg';
import '../../images/img/home/content/desk/img_3@2x.jpg';
import '../../images/img/home/content/desk/img_4.jpg';
import '../../images/img/home/content/desk/img_4@2x.jpg';
import '../../images/img/home/content/desk/img_5.jpg';
import '../../images/img/home/content/desk/img_5@2x.jpg';
import '../../images/img/home/content/desk/img_6.jpg';
import '../../images/img/home/content/desk/img_6@2x.jpg';
import '../../images/img/home/content/desk/img_7.jpg';
import '../../images/img/home/content/desk/img_7@2x.jpg';
import '../../images/img/home/content/desk/img_8.jpg';
import '../../images/img/home/content/desk/img_8@2x.jpg';
import '../../images/img/home/content/desk/img_9.jpg';
import '../../images/img/home/content/desk/img_9@2x.jpg';
import '../../images/img/home/content/desk/img_10.jpg';
import '../../images/img/home/content/desk/img_10@2x.jpg';

//============ homeAboutBrand======================//
import '../../images/img/homeAboutBrand/aboutBrandArrow.png';
import '../../images/img/homeAboutBrand/aboutBrandDesktop@1x.jpg';
import '../../images/img/homeAboutBrand/aboutBrandDesktop@2x.jpg';
import '../../images/img/homeAboutBrand/aboutBrandMob@1x.jpg';
import '../../images/img/homeAboutBrand/aboutBrandMob@2x.jpg';

//============ ourShowroom =========================//
import '../../images/img/page-showroom/desktop/01/showroom-desktop-01.jpg';
import '../../images/img/page-showroom/desktop/01/showroom-desktop-01@2x.jpg';
import '../../images/img/page-showroom/desktop/02/showroom-desktop-02.jpg';
import '../../images/img/page-showroom/desktop/02/showroom-desktop-02@2x.jpg';
import '../../images/img/page-showroom/desktop/03/showroom-desktop-03.jpg';
import '../../images/img/page-showroom/desktop/03/showroom-desktop-03@2x.jpg';
import '../../images/img/page-showroom/mobile/01/showroom-mobile-01.jpg';
import '../../images/img/page-showroom/mobile/01/showroom-mobile-01@2x.jpg';
import '../../images/img/page-showroom/mobile/02/showroom-mobile-02.jpg';
import '../../images/img/page-showroom/mobile/02/showroom-mobile-02@2x.jpg';
import '../../images/img/page-showroom/mobile/03/showroom-mobile-03.jpg';
import '../../images/img/page-showroom/mobile/03/showroom-mobile-03@2x.jpg';

//============ page-Brand======================//
import '../../images/img/brand/elena-des.jpg';
import '../../images/img/brand/elena-des@2x.jpg';
import '../../images/img/brand/elena-mob.jpg';
import '../../images/img/brand/elena-mob@2x.jpg';
import '../../images/img/brand/two-an-des.jpg';
import '../../images/img/brand/two-an-des@2x.jpg';
import '../../images/img/brand/two-an-mob.jpg';
import '../../images/img/brand/two-an-mob@2x.jpg';
import '../../images/img/brand/brand-video-image.jpg';

//============ starClients=========================//
import '../../images/img/page-clients/client-01/starClient-01.jpg';
import '../../images/img/page-clients/client-01/starClient-01@2x.jpg';
import '../../images/img/page-clients/client-01/starClient-01@3x.jpg';
import '../../images/img/page-clients/client-01/starClient-01@4x.jpg';
import '../../images/img/page-clients/client-02/starClient-02.jpg';
import '../../images/img/page-clients/client-02/starClient-02@2x.jpg';
import '../../images/img/page-clients/client-02/starClient-02@3x.jpg';
import '../../images/img/page-clients/client-02/starClient-02@4x.jpg';
import '../../images/img/page-clients/client-03/starClient-03.jpg';
import '../../images/img/page-clients/client-03/starClient-03@2x.jpg';
import '../../images/img/page-clients/client-03/starClient-03@3x.jpg';
import '../../images/img/page-clients/client-03/starClient-03@4x.jpg';
import '../../images/img/page-clients/client-04/starClient-04.jpg';
import '../../images/img/page-clients/client-04/starClient-04@2x.jpg';
import '../../images/img/page-clients/client-04/starClient-04@3x.jpg';
import '../../images/img/page-clients/client-04/starClient-04@4x.jpg';
import '../../images/img/page-clients/client-05/starClient-05.jpg';
import '../../images/img/page-clients/client-05/starClient-05@2x.jpg';
import '../../images/img/page-clients/client-05/starClient-05@3x.jpg';
import '../../images/img/page-clients/client-05/starClient-05@4x.jpg';
import '../../images/svg/clients-svg-original/clients-arrow-right.svg';
import '../../images/svg/clients-svg-original/clients-arrow-left.svg';
import '../../images/img/homeReviewsChat/chatImage@1x.png';
import '../../images/img/homeReviewsChat/chatImage@2x.png';
import '../../images/svg/homeReviewsChat/Foreground.svg';
import '../../images/svg/homeReviewsChat/Union.svg';

import '../../images/svg/homeReviewsChat/arrow-up-circle-fill.svg';

//============product===========//
import '../../images/img/product/handSewn/handSewn-desktop-1.jpg';
import '../../images/img/product/handSewn/handSewn-desktop-1@2x.jpg';
import '../../images/img/product/handSewn/handSewn-desktop-2.jpg';
import '../../images/img/product/handSewn/handSewn-desktop-2@2x.jpg';
import '../../images/img/product/handSewn/handSewn-mobile-1.jpg';
import '../../images/img/product/handSewn/handSewn-mobile-1@2x.jpg';
import '../../images/img/product/handSewn/handSewn-mobile-2.jpg';
import '../../images/img/product/handSewn/handSewn-mobile-2@2x.jpg';
import '../../images/img/product/handSewn/handSewn-bg-right.png';
import '../../images/img/product/handSewn/handSewn-bg-left.png';
import '../../images/img/product/productBin/product1.jpg';
import '../../images/img/product/productBin/product1@2x.jpg';
import '../../images/img/product/productBin/product2.jpg';
import '../../images/img/product/productBin/product2@2x.jpg';
import '../../images/svg/sprite.svg';
import '../../images/svg/thanks_for_ordering.svg';

// =======catalog========
import '../../images/svg/catalog/catalog.svg';
import '../../images/img/catalog/card-1.jpg';
import '../../images/img/catalog/card-1@2x.jpg';
import '../../images/img/catalog/card-2.jpg';
import '../../images/img/catalog/card-2@2x.jpg';
import '../../images/img/catalog/card-3.jpg';
import '../../images/img/catalog/card-3@2x.jpg';
import '../../images/img/catalog/card-4.jpg';
import '../../images/img/catalog/card-4@2x.jpg';
import '../../images/img/catalog/card-5.jpg';
import '../../images/img/catalog/card-5@2x.jpg';
import '../../images/img/catalog/card-6.jpg';
import '../../images/img/catalog/card-6@2x.jpg';
import '../../images/img/catalog/card-7.jpg';
import '../../images/img/catalog/card-7@2x.jpg';
import '../../images/img/catalog/card-8.jpg';
import '../../images/img/catalog/card-8@2x.jpg';
import '../../images/img/catalog/card-9.jpg';
import '../../images/img/catalog/card-9@2x.jpg';
import '../../images/img/catalog/card-10.jpg';
import '../../images/img/catalog/card-10@2x.jpg';
import '../../images/img/catalog/card-11.jpg';
import '../../images/img/catalog/card-11@2x.jpg';
import '../../images/img/catalog/card-12.jpg';
import '../../images/img/catalog/card-12@2x.jpg';
import '../../images/img/catalog/card-13.jpg';
import '../../images/img/catalog/card-13@2x.jpg';
import '../../images/img/catalog/card-14.jpg';
import '../../images/img/catalog/card-14@2x.jpg';
import '../../images/img/catalog/card-15.jpg';
import '../../images/img/catalog/card-15@2x.jpg';
import '../../images/img/catalog/card-16.jpg';
import '../../images/img/catalog/card-16@2x.jpg';
import '../../images/img/catalog/card-17.jpg';
import '../../images/img/catalog/card-17@2x.jpg';
import '../../images/img/catalog/card-18.jpg';
import '../../images/img/catalog/card-18@2x.jpg';
import '../../images/img/catalog/card-19.jpg';
import '../../images/img/catalog/card-19@2x.jpg';
import '../../images/img/catalog/card-1-desktop.jpg';
import '../../images/img/catalog/card-1-desktop@2x.jpg';
import '../../images/img/catalog/card-2-desktop.jpg';
import '../../images/img/catalog/card-2-desktop@2x.jpg';
import '../../images/img/catalog/card-3-desktop.jpg';
import '../../images/img/catalog/card-3-desktop@2x.jpg';
import '../../images/img/catalog/card-4-desktop.jpg';
import '../../images/img/catalog/card-4-desktop@2x.jpg';
import '../../images/img/catalog/card-5-desktop.jpg';
import '../../images/img/catalog/card-5-desktop@2x.jpg';
import '../../images/img/catalog/card-6-desktop.jpg';
import '../../images/img/catalog/card-6-desktop@2x.jpg';
import '../../images/img/catalog/card-7-desktop.jpg';
import '../../images/img/catalog/card-7-desktop@2x.jpg';
import '../../images/img/catalog/card-8-desktop.jpg';
import '../../images/img/catalog/card-8-desktop@2x.jpg';
import '../../images/img/catalog/card-9-desktop.jpg';
import '../../images/img/catalog/card-9-desktop@2x.jpg';
import '../../images/img/catalog/card-10-desktop.jpg';
import '../../images/img/catalog/card-10-desktop@2x.jpg';
import '../../images/img/catalog/card-11-desktop.jpg';
import '../../images/img/catalog/card-11-desktop@2x.jpg';
import '../../images/img/catalog/card-12-desktop.jpg';
import '../../images/img/catalog/card-12-desktop@2x.jpg';
import '../../images/img/catalog/card-13-desktop.jpg';
import '../../images/img/catalog/card-13-desktop@2x.jpg';
import '../../images/img/catalog/card-14-desktop.jpg';
import '../../images/img/catalog/card-14-desktop@2x.jpg';
import '../../images/img/catalog/card-15-desktop.jpg';
import '../../images/img/catalog/card-15-desktop@2x.jpg';
import '../../images/img/catalog/card-16-desktop.jpg';
import '../../images/img/catalog/card-16-desktop@2x.jpg';
import '../../images/img/catalog/card-17-desktop.jpg';
import '../../images/img/catalog/card-17-desktop@2x.jpg';
import '../../images/img/catalog/card-18-desktop.jpg';
import '../../images/img/catalog/card-18-desktop@2x.jpg';
import '../../images/img/catalog/card-19-desktop.jpg';
import '../../images/img/catalog/card-19-desktop@2x.jpg';
import '../../images/img/catalog/card-20-desktop.jpg';
import '../../images/img/catalog/card-20-desktop@2x.jpg';
// ============productInfo===========
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-1.jpg';
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-2.jpg';
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-3.jpg';
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-4.jpg';
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-5.jpg';
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-6.jpg';
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-1@2x.jpg';
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-2@2x.jpg';
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-3@2x.jpg';
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-4@2x.jpg';
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-5@2x.jpg';
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-6@2x.jpg';
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-1.jpg';
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-2.jpg';
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-3.jpg';
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-4.jpg';
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-5.jpg';
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-6.jpg';
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-1@2x.jpg';
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-2@2x.jpg';
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-3@2x.jpg';
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-4@2x.jpg';
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-5@2x.jpg';
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-6@2x.jpg';
import '../../images/svg/products/circle-black.svg';
import '../../images/svg/products/circle-red.svg';
import '../../images/svg/products/circle-grey.svg';
import '../../images/svg/products/circle-green.svg';
import '../../images/svg/products/circle-blue.svg';
import '../../images/svg/products/circle-white.svg';
import '../../images/svg/product/product-icon-close.svg';
import '../../images/svg/product/icon-product-delivery.svg';
import '../../images/svg/product/product-modal-button-close.svg';

//==============blockHelp=================//
import '../../images/svg/blockHelp/arrow.svg';
import '../../images/svg/blockHelp/cross.svg';
import '../../images/svg/blockHelp/helpChat.svg';
import '../../images/svg/blockHelp/helpPhone.svg';
import '../../images/svg/blockHelp/rectangleWhite.svg';

//============inInstagram===========//
import '../../images/img/page-in-instagram/we-are-in-insta-01.jpg';
import '../../images/img/page-in-instagram/we-are-in-insta-01@2x.jpg';
import '../../images/img/page-in-instagram/we-are-in-insta-02.jpg';
import '../../images/img/page-in-instagram/we-are-in-insta-02@2x.jpg';
import '../../images/img/page-in-instagram/we-are-in-insta-03.jpg';
import '../../images/img/page-in-instagram/we-are-in-insta-03@2x.jpg';
import '../../images/img/page-in-instagram/we-are-in-insta-04.jpg';
import '../../images/img/page-in-instagram/we-are-in-insta-04@2x.jpg';
import '../../images/img/page-in-instagram/we-are-in-insta-05.jpg';
import '../../images/img/page-in-instagram/we-are-in-insta-05@2x.jpg';

//===============payment===========================//

import '../../images/svg/product/product-icon-close.svg';
import '../../images/img/product/productBin/product1.jpg';
import '../../images/img/product/productBin/product1@2x.jpg';
import '../../images/img/product/productBin/product2.jpg';
import '../../images/img/product/productBin/product2@2x.jpg';

//===============payment===========================//
import '../../images/img/checkout/payment/buyers.jpg';
import '../../images/img/checkout/payment/buyers@2x.jpg';
import '../../images/img/checkout/payment/mirror_reflection.jpg';
import '../../images/img/checkout/payment/mirror_reflection@2x.jpg';
import '../../images/svg/murkup.svg';
import '../../images/svg/murkup_arow.svg';
//=========fitting=========================//
import '../../images/img/elean47390.jpg';
import '../../images/img/elean47390@2x.jpg';
import '../../images/img/fon.jpg';
import '../../images/svg/arrow-left.svg';
import '../../images/svg/arrow-right.svg';
//===============Reviews===========================//
import '../../images/img/Reviews/poster/Black2V.jpg';
import '../../images/img/Reviews/poster/23.jpg';
import '../../images/img/Reviews/poster/55.jpg';
import '../../images/img/Reviews/poster/78.jpg';

//=========tryOnModal===========//
import '../../images/svg/tryOnModal/check.svg';
import '../../images/svg/tryOnModal/crossTryOnModal.svg';
import '../../images/svg/tryOnModal/model.svg';
import '../../images/svg/tryOnModal/paiment.svg';
import '../../images/svg/tryOnModal/request.svg';
import '../../images/svg/tryOnModal/stylist.svg';
import '../../images/svg/tryOnModal/time.svg';

//=============delivery=====================
import '../../images/img/elean62862_1.jpg';
import '../../images/svg/Group.svg';
import '../../images/img/checkout/payment/buyers.jpg';
import '../../images/img/checkout/payment/buyers@2x.jpg';
import '../../images/img/checkout/payment/mirror_reflection.jpg';
import '../../images/img/checkout/payment/mirror_reflection@2x.jpg';
import '../../images/svg/murkup.svg';
import '../../images/svg/murkup_arow.svg';
