import '../../images/img/exampl.jpg';
import '../../images/svg/exampl.svg';
//=========== hero========================

import '../../images/img/page-hero/mobile/hero-title-01/hero-title-mobile-01.jpg';
import '../../images/img/page-hero/mobile/hero-title-01/hero-title-mobile-01@2x.jpg';
import '../../images/img/page-hero/mobile/hero-title-02/hero-title-mobile-02.jpg';
import '../../images/img/page-hero/mobile/hero-title-02/hero-title-mobile-02@2x.jpg';
import '../../images/img/page-hero/mobile/hero-title-03/hero-title-mobile-03.jpg';
import '../../images/img/page-hero/mobile/hero-title-03/hero-title-mobile-03@2x.jpg';
import '../../images/img/page-hero/mobile/hero-title-04/hero-title-mobile-04.jpg';
import '../../images/img/page-hero/mobile/hero-title-04/hero-title-mobile-04@2x.jpg';
import '../../images/img/page-hero/desktop/hero-title-01/hero-title-desktop-01.jpg';
import '../../images/img/page-hero/desktop/hero-title-01/hero-title-desktop-01@2x.jpg';
import '../../images/img/page-hero/desktop/hero-title-02/hero-title-desktop-02.jpg';
import '../../images/img/page-hero/desktop/hero-title-02/hero-title-desktop-02@2x.jpg';
import '../../images/img/page-hero/desktop/hero-title-03/hero-title-desktop-03.jpg';
import '../../images/img/page-hero/desktop/hero-title-03/hero-title-desktop-03@2x.jpg';
import '../../images/img/page-hero/desktop/hero-title-04/hero-title-desktop-04.jpg';
import '../../images/img/page-hero/desktop/hero-title-04/hero-title-desktop-04@2x.jpg';
import '../../images/svg/hero-svg-original/hero-arrow-left.svg';
import '../../images/svg/hero-svg-original/hero-arrow-right.svg';
//============ starClients=========================
import '../../images/img/page-clients/client-01/starClient-01.jpg';
import '../../images/img/page-clients/client-01/starClient-01@2x.jpg';
import '../../images/img/page-clients/client-01/starClient-01@3x.jpg';
import '../../images/img/page-clients/client-01/starClient-01@4x.jpg';
import '../../images/img/page-clients/client-02/starClient-02.jpg';
import '../../images/img/page-clients/client-02/starClient-02@2x.jpg';
import '../../images/img/page-clients/client-02/starClient-02@3x.jpg';
import '../../images/img/page-clients/client-02/starClient-02@4x.jpg';
import '../../images/img/page-clients/client-03/starClient-03.jpg';
import '../../images/img/page-clients/client-03/starClient-03@2x.jpg';
import '../../images/img/page-clients/client-03/starClient-03@3x.jpg';
import '../../images/img/page-clients/client-03/starClient-03@4x.jpg';
import '../../images/img/page-clients/client-04/starClient-04.jpg';
import '../../images/img/page-clients/client-04/starClient-04@2x.jpg';
import '../../images/img/page-clients/client-04/starClient-04@3x.jpg';
import '../../images/img/page-clients/client-04/starClient-04@4x.jpg';
import '../../images/img/page-clients/client-05/starClient-05.jpg';
import '../../images/img/page-clients/client-05/starClient-05@2x.jpg';
import '../../images/img/page-clients/client-05/starClient-05@3x.jpg';
import '../../images/img/page-clients/client-05/starClient-05@4x.jpg';
import '../../images/svg/clients-svg-original/clients-arrow-right.svg';
import '../../images/svg/clients-svg-original/clients-arrow-left.svg';
import '../../images/img/homeReviewsChat/chatImage@1x.png';
import '../../images/img/homeReviewsChat/chatImage@2x.png';
import '../../images/svg/homeReviewsChat/Foreground.svg'
import '../../images/svg/homeReviewsChat/Union.svg'
//============product===========
import '../../images/img/product/handSewn/handSewn-desktop-1.jpg';
import '../../images/img/product/handSewn/handSewn-desktop-1@2x.jpg';
import '../../images/img/product/handSewn/handSewn-desktop-2.jpg';
import '../../images/img/product/handSewn/handSewn-desktop-2@2x.jpg';
import '../../images/img/product/handSewn/handSewn-mobile-1.jpg';
import '../../images/img/product/handSewn/handSewn-mobile-1@2x.jpg';
import '../../images/img/product/handSewn/handSewn-mobile-2.jpg';
import '../../images/img/product/handSewn/handSewn-mobile-2@2x.jpg';
import '../../images/img/product/handSewn/handSewn-bg-right.png';
import '../../images/img/product/handSewn/handSewn-bg-left.png';
import '../../images/svg/sprite.svg';
import '../../images/svg/thanks_for_ordering.svg';
// ============productInfo===========
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-1.jpg'
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-2.jpg'
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-3.jpg'
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-4.jpg'
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-5.jpg'
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-1@2x.jpg'
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-2@2x.jpg'
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-3@2x.jpg'
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-4@2x.jpg'
import '../../images/img/products/mobile/tuxedo-and-vest-mobile-5@2x.jpg'
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-1.jpg'
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-2.jpg'
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-3.jpg'
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-4.jpg'
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-1@2x.jpg'
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-2@2x.jpg'
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-3@2x.jpg'
import '../../images/img/products/desktop/tuxedo-and-vest-mini-desktop-4@2x.jpg'
